server:
  port: 8085

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3307/parttime_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_ROOT_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

clock:
  max-distance: 500
  work-hour-round: 0.5

schedule:
  calculate-time: "01:00:00"